pipeline {
    agent any

    environment {
        NODE_ENV = 'production'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/sarwirr/pfa.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                    sh 'npm install --save-dev @types/express @types/multer'
                }
            }
        }

        stage('Load Environment Variables') {
            steps {
                dir('backend') {
                    script {
                        def envFile = readFile('.env')
                        envFile.split('\n').each { line ->
                            def keyVal = line.split('=')
                            if (keyVal.length == 2) {
                                env[keyVal[0]] = keyVal[1].trim()
                            }
                        }
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    sh 'npm test'
                }
            }
        }

        stage('Lint') {
            steps {
                dir('backend') {
                    sh 'npm run lint'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build or deployment failed.'
        }
    }
}
